name: Zw2Afk
version: 2.0.0
description: Damit kann man afk gehen oder wiederkommen
api-version: "1.14"
author: Zweistein2

softdepend: [SuperVanish]

main: de.zweistein2.Zw2Afk

commands:
  afk:
    description: Setzt dich afk
    usage: Nutze /<command> [Nachricht] um den Befehl richtig zu verwenden
  re:
    description: Setzt dich wieder in den Normalzustand
    usage: Nutze /<command> um den Befehl richtig zu verwenden
  reload:
    description: Lädt die Config neu
    usage: Nutze /<command> um den Befehl richtig zu verwenden
permissions:
  Zw2Afk.afk:
    description: weggehen
    default: true
  Zw2Afk.re:
    description: wiederkommen
    default: true
  Zw2Afk.reload:
    description: Config neuladen
    default: false